/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wy_bsdiffupdate_util_BsPatchNative */

#ifndef _Included_com_wy_bsdiffupdate_util_BsPatchNative
#define _Included_com_wy_bsdiffupdate_util_BsPatchNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wy_bsdiffupdate_util_BsPatchNative
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wy_bsdiffupdate_util_BsPatchNative_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
