/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_hpsvse_bsdiff_BsdiffNative */

#ifndef _Included_com_hpsvse_bsdiff_BsdiffNative
#define _Included_com_hpsvse_bsdiff_BsdiffNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hpsvse_bsdiff_BsdiffNative
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_hpsvse_bsdiff_BsdiffNative_diff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
